name: Autograding

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      id: pytest
      run: |
        pytest --tb=short --maxfail=5 > results.log
        if grep -q "FAILED" results.log; then exit 1; fi

    - name: Generate results
      run: echo "::set-output name=score::$(grep -oP '(?<=== )[0-9]+ passed' results.log | awk '{print $1}')"

outputs:
  score: ${{ steps.pytest.outputs.score }}
